# This is a basic workflow to help you get started with Actions
name: Build and publish

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [dokken/jupyterbook]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Weekly build on Mondays at 8 am
  schedule:
    - cron: "0 8 * * 1"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: dokken92/dolfinx_custom:v0.5.0

    env:
      HDF5_MPI: "ON"
      CC: mpicc
      HDF5_DIR: "/usr/local/"
      DISPLAY: ":99.0"
      PYVISTA_OFF_SCREEN: true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Test complex notebooks in parallel
        run: |
          export PKG_CONFIG_PATH=/usr/local/dolfinx-complex/lib/pkgconfig:$PKG_CONFIG_PATH
          export PETSC_ARCH=linux-gnu-complex-32
          export PYTHONPATH=/usr/local/dolfinx-complex/lib/python3.10/dist-packages:$PYTHONPATH
          export LD_LIBRARY_PATH=/usr/local/dolfinx-complex/lib:$LD_LIBRARY_PATH
          pip3 uninstall pyvista -y
          pip3 install pyvista --upgrade
          cd chapter1
          mpirun -n 2 python3 complex_mode.py
 

      - name: Install dependencies
        run: pip3 install notebook nbconvert jupyter-book --upgrade
      - name: Test notebooks in parallel
        run: |
          python3 -c "from pyvista import start_xvfb; start_xvfb(0.1)"
          cd chapter1
          mpirun -n 2 python3 fundamentals_code.py
          mpirun -n 2 python3 membrane_code.py
          cd ../chapter2
          mpirun -n 2 python3 diffusion_code.py
          mpirun -n 2 python3 heat_code.py
          mpirun -n 2 python3 linearelasticity_code.py
          mpirun -n 2 python3 hyperelasticity.py
          mpirun -n 2 python3 nonlinpoisson_code.py
          mpirun -n 2 python3 ns_code1.py
          mpirun -n 2 python3 ns_code2.py
          cd ../chapter3
          mpirun -n 3 python3 neumann_dirichlet_code.py
          mpirun -n 3 python3 multiple_dirichlet.py
          mpirun -n 3 python3 subdomains.py
          mpirun -n 3 python3 robin_neumann_dirichlet.py
          mpirun -n 3 python3 component_bc.py
          mpirun -n 3 python3 em.py
          cd ../chapter4
          mpirun -n 3 python3 solvers.py
          mpirun -n 3 python3 convergence.py
          mpirun -n 3 python3 compiler_parameters.py

      # Runs a single command using the runners shell
      - name: Build the book
        run: |
          PYVISTA_JUPYTER_BACKEND=static PYVISTA_OFF_SCREEN=false jupyter-book build  -W .
      # Push book to HTML to github pages
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.5.9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/html
